<!-- START Google Trusted Stores Order -->
<div id="gts-order" style="display:none;" translate="no">
    <!-- start order and merchant information -->
    <span id="gts-o-id">MERCHANT_ORDER_ID</span>
    <span id="gts-o-email">CUSTOMER_EMAIL</span>
    <span id="gts-o-country">CUSTOMER_COUNTRY</span>
    <span id="gts-o-currency">CURRENCY</span>
    <span id="gts-o-total">ORDER_TOTAL</span>
    <span id="gts-o-discounts">ORDER_DISCOUNTS</span>
    <span id="gts-o-shipping-total">ORDER_SHIPPING</span>
    <span id="gts-o-tax-total">ORDER_TAX</span>
    <span id="gts-o-est-ship-date">ORDER_EST_SHIP_DATE</span>
    <span id="gts-o-est-delivery-date">ORDER_EST_DELIVERY_DATE</span>
    <span id="gts-o-has-preorder">HAS_BACKORDER_PREORDER</span>
    <span id="gts-o-has-digital">HAS_DIGITAL_GOODS</span>
    <!-- end order and merchant information -->

    <!-- start repeated item specific information -->
    <!-- item example: this area repeated for each item in the order -->
    <span class="gts-item">
        <span class="gts-i-name">ITEM_NAME</span>
        <span class="gts-i-price">ITEM_PRICE</span>
        <span class="gts-i-quantity">ITEM_QUANTITY</span>
        <span class="gts-i-prodsearch-id">ITEM_GOOGLE_SHOPPING_ID</span>
        <span class="gts-i-prodsearch-store-id">ITEM_GOOGLE_SHOPPING_ACCOUNT_ID</span>
    </span>
    <!-- end item 1 example -->
    <!-- end repeated item specific information -->
</div>
<!-- END Google Trusted Stores Order -->
