<!-- START Google Trusted Stores Order -->
<div id="gts-order" style="display:none;" translate="no">
    <!-- start order and merchant information -->
    <span id="gts-o-id">{{code}}</span>
    <span id="gts-o-domain">{{code}}</span>
    <span id="gts-o-email">{{code}}</span>
    <span id="gts-o-country">{{code}}</span>
    <span id="gts-o-currency">{{code}}</span>
    <span id="gts-o-total">{{code}}</span>
    <span id="gts-o-discounts">{{code}}</span>
    <span id="gts-o-shipping-total">{{code}}</span>
    <span id="gts-o-tax-total">{{code}}</span>
    <span id="gts-o-est-ship-date">{{code}}</span>
    <span id="gts-o-has-preorder">{{code}}</span>
    <span id="gts-o-has-digital">{{code}}</span>
    <!-- end order and merchant information -->

    <!-- start repeated item specific information -->
    <!-- (repeats put inside loop over items) -->
    <span class="gts-item">
        <span class="gts-i-name">{{code}}</span>
        <span class="gts-i-price">{{code}}</span>
        <span class="gts-i-quantity">{{code}}</span>
        <!-- CDATA[<span class="gts-i-prodsearch-id">{{code}}</span>] -->
        <!-- CDATA[<span class="gts-i-prodsearch-store-id">{{code}}</span>] -->
    </span>
    <!-- end repeated item specific information -->
</div>
<!-- END Google Trusted Stores Order -->
